### ISSUE TITLE
On android: Unable to locate package tur-repo

### ISSUE THREAD

**Issue by RuairiSpain** [OvalRaptor/VSCodeOnAndroid#1]
I got this error: Unable to locate package tur-repo

Maybe tur-repo is already part of tmux?
I tried:
apt-get install -y build-essential gdb binutils wget pkg-config code-server

But then it errors:
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package code-server

**Comment by OvalRaptor** [comment]
Code-server cannot be installed without tur-repo. I've tried to replicate your issue however the only answer I can come up with is you haven't updated your Termux packages before installing tur-repo. Make sure you type apt update;apt upgrade on every fresh install of termux.
